### PR TITLE
Register AProVE

### PR DESCRIPTION
**Pull request by fmeyer3141**
Added configurations for AProVE.

### CODE REVIEW

**Comment by AkihisaYamada** [comment]
@fmeyer3141 It seems [this version](https://www.starexec.org/starexec/secure/details/configuration.jsp?id=671179) is not accessible from me. Can you give the permission?

**Comment by fmeyer3141** [comment]
This is strange, what error message do you get?
I am able to access the configuration and download the solver in the "private mode" of my browser (where I am not logged in) so I think it should be accessible.

**Comment by AkihisaYamada** [comment]
Indeed. It seems there was a change in StarExec so that I go into a so wrong state that I couldn't see the config. But probably I can figure it out... thanks!

**Comment by AkihisaYamada** [comment]
@fmeyer3141 Sorry, the problem was [this one](https://www.starexec.org/starexec/secure/details/configuration.jsp?id=671239). Please make it accessible like the other ones.

**Comment by cfuhs** [comment]
Permission added (I think/hope - publicness does not seem to be a property of the solver itself). The solver should be accessible here: [https://www.starexec.org/starexec/secure/details/solver.jsp?id=41408](https://www.starexec.org/starexec/secure/details/solver.jsp?id=41408)

**Comment by cfuhs** [comment]
Permission added (I think/hope - publicness does not seem to be a property of the solver itself, but rather of the surrounding space). The solver should be accessible here: [https://www.starexec.org/starexec/secure/details/solver.jsp?id=41408](https://www.starexec.org/starexec/secure/details/solver.jsp?id=41408) Apologies for this!

**Comment by AkihisaYamada** [comment]
OK it's now started.

**Comment by AkihisaYamada** [comment]
I don't seem to have permission for 671123 and 671224, too.

**Pull request merged**
